name = "job-circular-proxy"
main = "edge-proxy.js"
compatibility_date = "2024-01-01"

[vars]
WEBHOOK_SECRET = "sync-all-data-secret-2026"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ea9b95e256ed4e46999d1a13dcc19edf"

[[queues.producers]]
queue = "live-exam-queue"
binding = "EXAM_QUEUE"

[[queues.consumers]]
queue = "live-exam-queue"
max_batch_size = 50
max_batch_timeout = 5
