android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
systemProp.http.socketTimeout=600000
systemProp.http.connectionTimeout=600000
systemProp.https.socketTimeout=600000
systemProp.https.connectionTimeout=600000
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
