/**
 * Text and HTML sanitization utilities for Job Circular
 */

/**
 * Strips all HTML tags and decodes common HTML entities from a string.
 * Ensures clean plain-text output for card titles, organization names, and descriptions.
 * 
 * @param {string|object} input 
 * @returns {string}
 */
export function stripHtmlTags(input) {
  if (!input) return '';
  
  let str = input;
  if (typeof str === 'object') {
    str = str.bn || str.en || str.title || str.name || str.text || '';
  }
  if (typeof str !== 'string') {
    str = String(str || '');
  }

  // Replace block endings and line breaks with spaces so words do not concatenate
  let cleaned = str
    .replace(/<br\s*[\/]?>/gi, ' ')
    .replace(/<\/(p|div|h[1-6]|li|tr|th|td|blockquote)>/gi, ' ')
    .replace(/<[^>]*>/g, '');

  // Decode HTML entities
  cleaned = cleaned
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&#34;/g, '"')
    .replace(/&amp;/g, '&')
    .replace(/&#38;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&#60;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#62;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#160;/g, ' ')
    .replace(/&#(\d+);/g, (_, dec) => {
      try {
        return String.fromCharCode(parseInt(dec, 10));
      } catch {
        return '';
      }
    })
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => {
      try {
        return String.fromCharCode(parseInt(hex, 16));
      } catch {
        return '';
      }
    });

  // Collapse multiple whitespaces and newlines
  return cleaned.replace(/\s+/g, ' ').trim();
}

/**
 * Sanitizes rich text HTML for descriptions to prevent invisible text
 * caused by dark-mode copied styles (e.g. color: rgb(255, 255, 255)).
 * 
 * @param {string} html 
 * @returns {string}
 */
export function sanitizeRichHtml(html) {
  if (!html || typeof html !== 'string') return '';
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
    .replace(/color:\s*(#fff(fff)?|white|rgb\(\s*255\s*,\s*255\s*,\s*255\s*\))/gi, 'color: inherit');
}

/**
 * Cleans option text by removing duplicated choice prefixes (e.g. "(a)", "A.", "(ক)", "ক)"),
 * stripping HTML tags, and decoding entities like &nbsp; into clean plain text.
 */
export function cleanOptionText(input) {
  if (!input) return '';
  let str = input;
  if (typeof str === 'object') {
    str = str.bn || str.en || str.title || str.name || str.text || '';
  }
  str = String(str || '');

  // Strip all HTML tags and decode entities first
  str = stripHtmlTags(str);

  // Remove duplicated option prefix if present in the text
  const prefixPatterns = [
    /^\([a-d]\)\s*/i,   // (a), (b), (c), (d)
    /^[a-d][\.\)]\s*/i, // a., a), b., b)
    /^\([ক-ঘ]\)\s*/,   // (ক), (খ), (গ), (ঘ)
    /^[ক-ঘ][\।\)]\s*/, // ক।, ক), খ।, খ)
    /^\(\d+\)\s*/,     // (1), (2)
    /^\d+[\.\)]\s*/    // 1., 1)
  ];
  prefixPatterns.forEach(pattern => {
    str = str.replace(pattern, '');
  });

  return str.trim();
}

/**
 * Sanitizes rich text HTML for questions and explanations.
 * - Strips harmful scripts.
 * - Removes intrusive inline styling generated by contentEditable/browsers
 *   (font-family, font-size, line-height, conflicting rgb colors) while keeping
 *   valid HTML markup like <b>, <i>, <u>, <sup>, <sub>, <code>, <p>, <br>, <strong>, etc.
 * - Converts non-breaking spaces &nbsp; to normal spaces.
 * - Unwraps redundant styled spans.
 */
export function sanitizeQuestionHtml(input) {
  if (!input) return '';
  let html = input;
  if (typeof html === 'object') {
    html = html.bn || html.en || html.title || html.name || html.text || '';
  }
  html = String(html || '');

  // Remove script tags
  html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');

  // Strip intrusive inline styling from contentEditable
  html = html.replace(/font-family:\s*[^;"]*;?/gi, '');
  html = html.replace(/font-size:\s*[^;"]*;?/gi, '');
  html = html.replace(/line-height:\s*[^;"]*;?/gi, '');
  html = html.replace(/color:\s*(#fff(fff)?|white|rgb\(\s*255\s*,\s*255\s*,\s*255\s*\)|rgb\(\s*51\s*,\s*65\s*,\s*85\s*\));?/gi, '');
  html = html.replace(/background(-color)?:\s*[^;"]*;?/gi, '');

  // Clean empty style attributes
  html = html.replace(/\s*style=(["'])\s*\1/gi, '');

  // Unwrap useless spans that have no attributes left: <span>text</span> -> text
  let prev;
  let loops = 0;
  do {
    prev = html;
    html = html.replace(/<span>([\s\S]*?)<\/span>/gi, '$1');
    loops++;
  } while (html !== prev && loops < 10);

  // Replace &nbsp; with normal space
  html = html.replace(/&nbsp;/g, ' ');

  return html.trim();
}
